- name: Update Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml


- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Update Alerts Configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
  loop: "{{ alert_files }}"



- name: Update AlertManager Configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml


- name: Restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted


