- name: Create Application User
  ansible.builtin.user:
    name: roboshop

- name: Delete old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory


- name: Download and Extract {{ component }} Content
  ansible.builtin.unarchive:
    src: https://admin:admin123@nexus.devopsb71services.site:8081/repository/{{ component }}//{{ component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes


#Download from S3
#- name: Download and Extract {{ component }} Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes


