route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "email"
receivers:
  - name: "email"
    email_configs:
      - to: sritirumala30@gmail.com
        from: sritirumala30@gmail.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "AKIARXN4WYHHE6IME5RZ"
        auth_password: "BJr6I2KpEDczIZaTw94tI4N7YTxeE6n5VK91R2l7ptrg"
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'prod', 'instance']
