groups:
  - name: roboshop-service-alerts
    rules:
      - alert: Service Down Alert - Payment Service
        expr: node_systemd_unit_state{exported_name="payment.service" ,state="active"}
        for: 30s
        labels:
          severity: critical
          appName: Payment
        annotations:
          summary: Service Down on Some server - Service Name - cart.service
